config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  resources :users
  resources :event
  root 'event#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event 
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances 
    has_many :users, :through => :attendances

    validates :start_date, presence: true
    validates :duration, presence: true #bon trouver la méthode piour nombre multiple de 5
    validates :title, presence: true
    validates :description, presence: true, length: {minimum: 20, maximum: 1000}  
    validates :price, presence: true, numericality: {greater_than: 1, less_than: 1001}
    validates :location, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 

    has_many :attendances
    has_many :events, :through => :attendances

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController

    def index 
        @events = Event.all
    end 

    def show 
    end 

    def new 
        @events = Event.all
    end 

    def create 
    end 

    def edit  
    end 

    def update 
    end 

    def destroy
    end 
end 

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index  
    end 

    def show 
        @users = User.all
    end 

    def new 
    end 

    def create 
    end 

    def edit  
    end 

    def update 
    end 

    def destroy
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/event/index.html.erb
<h1>Привет, Добро Пожаловать</h1>
<h3>Voici la liste de nos events</h3>

<h6>Tu veux créer ton event appuies ici <a class="btn btn-secondary" <%= link_to "Creer event", new_event_path %>></h6>

<div class="ol-sm-4 mb-3">
<% @events.each do |event|%>
<div class="card">
<div class="card-body">
      <h2 class="card-title"> Nom de l'event:  <%=  event.title  %> </h2>
        <p class="card-text"> Début:  <%= event.start_date %> </p>
        <p class="card-text"> Durée: <%= event.duration %> </p>
         <p lass="card-text"> Description:<%= event.description %> </p>
          <p lass="card-text"> Prix: <%= event.price %>€ </p>
           <p lass="card-text"> Localisation: <%= event.location %> </p>
            <p><a class="btn btn-secondary" <%= link_to "Voir l'évènement", event_path(event.id)%></a></p>
      </div>
    </div>
  </div>
<% end %>

app/views/event/new.html.erb
<h1> New event oui tu as créé la page incroyable !</h1>

<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Title</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Titre">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Location</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Location">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="Adresse">
  </div>
  
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">Date</label>
      <input type="text" class="form-control" id="Date">
    </div>
    
  <div class="form-row">
    <div class="form-group col-md-5">
      <label for="inputCity">Duration</label>
      <input type="text" class="form-control" id="Date">
    </div>

    <div class="form-group col-md-3">
      <label for="inputZip">Duration</label>
      <input type="text" class="form-control" id="Duration">
    </div>
  </div>

    </div>
  </div>
  <button type="submit" class="btn btn-primary">Bête de soirée incomming</button>
</form>

app/views/event/show.html.erb
<h1> <%= Event.find(params[:id]).title %> </h1><br/>

<p> Début: <%= Event.find(params[:id]).start_date %> <br/>
    Durée: <%= Event.find(params[:id]).duration %> <br/>
    Description: <%= Event.find(params[:id]).description %> <br/>
    Prix: <%= Event.find(params[:id]).price %> <br/>
    Localisation: <%= Event.find(params[:id]).location %> <br/>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteAlike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css" rel="stylesheet" integrity="sha384-N8DsABZCqc1XWbg/bAlIDk7AS/yNzT5fcKzg/TwfmTuUqZhGquVmpb5VvfmLcMzp" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" <%= link_to "Rumbah", root_path %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to "Créer un Event", new_event_path %></a> 
    </li>
    <li class="nav-item">
      <a class="nav-link" <%href="#"%>>Profil</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Disabled</a>
    </li>
    <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

  </ul>

</nav>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<html>
    salut 
    
</html>